In [3]:
# 24I-6034 ______ HAMZA FAHEEM ________ DS-5B _______ DAV LAB 01

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("adult - adult.csv")
df.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education.num   32561 non-null  int64
 5   marital.status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital.gain    32561 non-null  int64
 11  capital.loss    32561 non-null  int64
 12  hours.per.week  32561 non-null  int64
 13  native.country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [5]:
df.describe()

,age,fnlwgt,education.num,capital.gain,capital.loss,hours.per.week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [9]:
# TASK 1
df.replace(['?', ' ?'], np.nan, inplace = True)
missingVals = df.isnull().sum()
missingVals

age                  0
workclass         1836
fnlwgt               0
education            0
education.num        0
marital.status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital.gain         0
capital.loss         0
hours.per.week       0
native.country     583
income               0
dtype: int64

In [10]:
# TASK 2
missingValsPerc = (missingVals / len(df)) * 100
missingValsPerc

age               0.000000
workclass         5.638647
fnlwgt            0.000000
education         0.000000
education.num     0.000000
marital.status    0.000000
occupation        5.660146
relationship      0.000000
race              0.000000
sex               0.000000
capital.gain      0.000000
capital.loss      0.000000
hours.per.week    0.000000
native.country    1.790486
income            0.000000
dtype: float64

In [13]:
# TASK 3
columnsWithUnusualValz = ['workclass', 'occupation', 'native.country']

for c in columnsWithUnusualValz:
    df[c].fillna('Unknown', inplace = True)

print("Total number of missing values = ", df.isnull().sum().sum())

Total number of missing values =  0

In [15]:
# TASK 4
exactDuplis = df.duplicated().sum()
print("Duplicated Rows: ", exactDuplis)

featuresOnly = [c for c in df.columns if c != 'income']
featuresDupli = df.duplicated(subset = featuresOnly).sum()
print("Duplicate rows after excluding the income column = ", featuresDupli)

Duplicated Rows:  24
Duplicate rows after excluding the income column =  25

In [20]:
# TASK 5
colsToFocusOn = ['education', 'marital.status', 'native.country']
print("Getting unique values :>")
for c in colsToFocusOn:
    print(f"Unique values in {c} = ")
    print(df[c].unique())
    print("\n")

objColz = df.select_dtypes(include = ['object']).columns
for c in objColz:
    df[c] = df[c].str.strip()

print("<-- After applying str.strip() -->")
for c in colsToFocusOn:
    print(f"Unique Values in brand new {c} = ")
    print(df[c].unique()[:10])
    print("\n")

Getting unique values :>
Unique values in education =
['HS-grad' 'Some-college' '7th-8th' '10th' 'Doctorate' 'Prof-school'
 'Bachelors' 'Masters' '11th' 'Assoc-acdm' 'Assoc-voc' '1st-4th' '5th-6th'
 '12th' '9th' 'Preschool']


Unique values in marital.status =
['Widowed' 'Divorced' 'Separated' 'Never-married' 'Married-civ-spouse'
 'Married-spouse-absent' 'Married-AF-spouse']


Unique values in native.country =
['United-States' 'Unknown' 'Mexico' 'Greece' 'Vietnam' 'China' 'Taiwan'
 'India' 'Philippines' 'Trinadad&Tobago' 'Canada' 'South'
 'Holand-Netherlands' 'Puerto-Rico' 'Poland' 'Iran' 'England' 'Germany'
 'Italy' 'Japan' 'Hong' 'Honduras' 'Cuba' 'Ireland' 'Cambodia' 'Peru'
 'Nicaragua' 'Dominican-Republic' 'Haiti' 'El-Salvador' 'Hungary'
 'Columbia' 'Guatemala' 'Jamaica' 'Ecuador' 'France' 'Yugoslavia'
 'Scotland' 'Portugal' 'Laos' 'Thailand' 'Outlying-US(Guam-USVI-etc)']


<-- After applying str.strip() -->
Unique Values in brand new education =
['HS-grad' 'Some-college' '7th-8th' '10th' 'Doctorate' 'Prof-school'
 'Bachelors' 'Masters' '11th' 'Assoc-acdm']


Unique Values in brand new marital.status =
['Widowed' 'Divorced' 'Separated' 'Never-married' 'Married-civ-spouse'
 'Married-spouse-absent' 'Married-AF-spouse']


Unique Values in brand new native.country =
['United-States' 'Unknown' 'Mexico' 'Greece' 'Vietnam' 'China' 'Taiwan'
 'India' 'Philippines' 'Trinadad&Tobago']

In [25]:
# TASK 6 (A)
print(df.describe())
print("-----------------------------------------------------------------")
print(df.describe(include = ['object']))

                age        fnlwgt  education.num  capital.gain  capital.loss  \
count  32561.000000  3.256100e+04   32561.000000  32561.000000  32561.000000
mean      38.581647  1.897784e+05      10.080679   1077.648844     87.303830
std       13.640433  1.055500e+05       2.572720   7385.292085    402.960219
min       17.000000  1.228500e+04       1.000000      0.000000      0.000000
25%       28.000000  1.178270e+05       9.000000      0.000000      0.000000
50%       37.000000  1.783560e+05      10.000000      0.000000      0.000000
75%       48.000000  2.370510e+05      12.000000      0.000000      0.000000
max       90.000000  1.484705e+06      16.000000  99999.000000   4356.000000

       hours.per.week
count    32561.000000
mean        40.437456
std         12.347429
min          1.000000
25%         40.000000
50%         40.000000
75%         45.000000
max         99.000000
-----------------------------------------------------------------
       workclass education      marital.status      occupation relationship  \
count      32561     32561               32561           32561        32561
unique         9        16                   7              15            6
top      Private   HS-grad  Married-civ-spouse  Prof-specialty      Husband
freq       22696     10501               14976            4140        13193

         race    sex native.country income
count   32561  32561          32561  32561
unique      5      2             42      2
top     White   Male  United-States  <=50K
freq    27816  21790          29170  24720

In [26]:
# TASK 6 (B)
ageMean = df['age'].mean()
ageMedian = df['age'].median()
hoursMean = df['hours.per.week'].mean()
hoursMedian = df['hours.per.week'].median()

print("Age Mean = ", ageMean)
print("Age Median = ", ageMedian)
print("Hours/Week Mean = ", hoursMean)
print("Hours/Week Median = ", hoursMedian)

Age Mean =  38.58164675532078
Age Median =  37.0
Hours/Week Mean =  40.437455852092995
Hours/Week Median =  40.0

In [35]:
# TASK 7
# --- (A) ---
mostCommonOccupation = df['occupation'].value_counts().index[0]
print(f"Most Common Occupation = {mostCommonOccupation} \n")

# --- (B) ---
sexDistribution = df['sex'].value_counts(normalize = True) * 100
print(f"Sex Distribution = {sexDistribution}\n")

# --- (C) ---
incomeDistribution = df['income'].value_counts(normalize = True) * 100
print(f"Income Distribution = {incomeDistribution}")

Most Common Occupation = Prof-specialty

Sex Distribution = sex
Male      66.920549
Female    33.079451
Name: proportion, dtype: float64

Income Distribution = income
<=50K    75.919044
>50K     24.080956
Name: proportion, dtype: float64

In [36]:
# TASK 8
df['education'] = df['education'].str.strip()

cnsistncy = df.groupby('education')['education.num'].unique()
print(cnsistncy)

inconsistentMapping = cnsistncy[cnsistncy.apply(len) > 1]

if len(inconsistentMapping) == 0:
    print("No inconsistency found :>")
else:
    print("Inconsistencies found!!!")
    print(inconsistentMapping)

education
10th             [6]
11th             [7]
12th             [8]
1st-4th          [2]
5th-6th          [3]
7th-8th          [4]
9th              [5]
Assoc-acdm      [12]
Assoc-voc       [11]
Bachelors       [13]
Doctorate       [16]
HS-grad          [9]
Masters         [14]
Preschool        [1]
Prof-school     [15]
Some-college    [10]
Name: education.num, dtype: object
No inconsistency found :>

In [41]:
# TASK 9
import sqlite3

conn = sqlite3.connect(':memory:')
df.to_sql('adult_income', conn, index = False, if_exists = 'replace')

qFiltered = "SELECT * FROM adult_income WHERE age > 30"
df_FilteredBySQL = pd.read_sql_query(qFiltered, conn)

qAll = "SELECT * FROM adult_income"
df_All = pd.read_sql_query(qAll, conn)

print(f"Original CSV Data-Frame shape: {df.shape}")
print(f"Full SQL Extraction shape: {df_All.shape}")
print(f"Filtered SQL shape (age > 30): {df_FilteredBySQL.shape}")
conn.close()

Original CSV Data-Frame shape: (32561, 15)
Full SQL Extraction shape: (32561, 15)
Filtered SQL shape (age > 30): (21989, 15)

### TASK 10 ###
-> The provided dataset has 32,516 rows & 15 columns.

-> Initially there were no missing values however after including '?', we got ~4000 missing values. Replacing Whitespaces and doing fillna('Unknown'), we cleaned the dataset.

-> From EDA, We got distribution of Sex (Male and Female) & Income (<= 50K and >50K).

-> Prof-Speciality is the most common occupation.

-> Removed duplicate values as it would've caused more biasness and slight distortion from actual correct numbers.